In [ ]:
# 1. Print number from 1 to 5 using a while loop.

num = 1

while num <= 5:
  print(num)
  num += 1

1
2
3
4
5

In [5]:
# 2. Calculate the sum of numbers from 1 to 10 using a while loop.

num = 1

sum = 0

while num <= 10:
  sum += num

  num += 1

print(sum)

55

In [ ]:
# 3. Calculate the factorial of a number using a for loop.

n = 4

factorial = 1

for i in range(1, n+1):
  factorial *= i


print(factorial)

24

In [ ]:
# 4. Count the number of vowels in a string using a for loop.

vowel = 'a','e','i','o','u'

for i in range(5):
  count = i+1, vowel[i]
  print(count)

(1, 'a')
(2, 'e')
(3, 'i')
(4, 'o')
(5, 'u')

In [ ]:
# 5. Print a pattern using nested loops.

for i in range(5):
  for j in range(1, i+1):
    print(j, end=' ')
  print()

1
1 2
1 2 3
1 2 3 4

In [ ]:
rows = 1
columns = 1
while rows <= 5:
  while columns <= rows:
    print("*"*columns, end=' ')
    columns += 1
  print()
  rows += 1

*
**
***
****
*****

In [3]:
# 6. Generate a multiplication table using nested loops.

num = 6

for i in range(1, num):
  for j in range(1, 11):
    multiplication = i * j
    print(f"{i} * {j} = {multiplication}")
  print()

1 * 1 = 1
1 * 2 = 2
1 * 3 = 3
1 * 4 = 4
1 * 5 = 5
1 * 6 = 6
1 * 7 = 7
1 * 8 = 8
1 * 9 = 9
1 * 10 = 10

2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20

3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
3 * 10 = 30

4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
4 * 10 = 40

5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50

In [4]:
row = 1

while row < 6:
  col = 1
  while col < 11:
    print(f"{row} * {col} = {row * col}")
    col +=1
  print()
  row += 1

1 * 1 = 1
1 * 2 = 2
1 * 3 = 3
1 * 4 = 4
1 * 5 = 5
1 * 6 = 6
1 * 7 = 7
1 * 8 = 8
1 * 9 = 9
1 * 10 = 10

2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20

3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
3 * 10 = 30

4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
4 * 10 = 40

5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50